# Generated by Django 2.2.5 on 2019-10-18 19:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_credentials',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=30)),
                ('about_user', models.TextField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.login_credentials')),
            ],
        ),
    ]
