# Generated by Django 2.2.6 on 2019-10-18 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
    ]
