# Generated by Django 2.2.6 on 2019-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0006_auto_20191019_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_credentials',
            name='email',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
