# Generated by Django 2.2.6 on 2019-10-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0008_auto_20191019_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
