# Generated by Django 2.2.6 on 2019-10-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0009_auto_20191030_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(default='blank.png', max_length=30, upload_to=''),
        ),
    ]
