# Generated by Django 2.2.6 on 2019-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0011_auto_20191030_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.CharField(default='blank.png', max_length=30),
        ),
    ]
