# Generated by Django 2.2.6 on 2019-10-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0012_auto_20191030_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='user_images/'),
        ),
    ]
