# Generated by Django 2.2.6 on 2019-10-29 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_details', '0013_auto_20191030_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.ImageField(default='', upload_to='user_images/')),
                ('about_user', models.TextField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
