# Generated by Django 2.2.6 on 2019-10-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0014_user_profile_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='user_images/'),
        ),
    ]
