# Generated by Django 2.2.6 on 2019-10-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0016_auto_20191030_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_info',
            name='about_user',
        ),
    ]
