# Generated by Django 2.2.6 on 2019-10-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0018_user_profile_info_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_info',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
