# Generated by Django 2.2.6 on 2019-10-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0019_user_profile_info_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='users',
            name='sex',
        ),
    ]
