# Generated by Django 2.2.6 on 2019-10-30 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_details', '0020_auto_20191030_1048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
