# Generated by Django 2.2.6 on 2019-11-02 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_details', '0001_initial'),
        ('movie_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(max_length=1)),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_details.movie_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Profile_Info')),
            ],
        ),
    ]
