# Generated by Django 2.2.6 on 2019-10-30 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_library',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Profile_Info'),
        ),
    ]
