# Generated by Django 2.2.6 on 2019-11-04 10:32

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filmstars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('news_id', models.IntegerField(default='', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('news_message', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('news_dt', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 10, 32, 1, 135494, tzinfo=utc))),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmstars.filmstars')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_details.movie_details')),
            ],
        ),
        migrations.CreateModel(
            name='news_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 10, 32, 1, 135914, tzinfo=utc))),
                ('approved_comments', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='latest_news.latest_news')),
            ],
        ),
    ]
