# Generated by Django 2.2.6 on 2019-10-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_news',
            name='images',
        ),
    ]
