# Generated by Django 2.2.6 on 2019-11-03 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0002_auto_20191103_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='news_dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 51, 37, 108111, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='news_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2019, 11, 3, 12, 51, 37, 108554, tzinfo=utc))),
                ('approved_comments', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='latest_news.latest_news')),
            ],
        ),
    ]
