# Generated by Django 2.2.6 on 2019-11-06 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0003_auto_20191104_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest_news',
            name='news_dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 9, 46, 16, 930967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 9, 46, 16, 931414, tzinfo=utc)),
        ),
    ]
