# Generated by Django 2.2.6 on 2019-11-02 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_information',
            fields=[
                ('patch_date', models.DateTimeField(blank=True, null=True)),
                ('version_id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('patch_notes', models.TextField(max_length=1000)),
                ('number_of_users', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('copyright_notice', models.TextField(max_length=1000)),
                ('t_n_c', models.TextField(max_length=30)),
            ],
        ),
    ]
