# Generated by Django 2.2.6 on 2019-10-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='general_information',
            name='patch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
