# Generated by Django 2.2.6 on 2019-10-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_information', '0002_general_information_patch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_information',
            name='copyright_notice',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='general_information',
            name='patch_notes',
            field=models.TextField(max_length=1000),
        ),
    ]
