# Generated by Django 2.2.6 on 2019-10-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latest_news', '0001_initial'),
        ('movie_and_actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_and_actors',
            name='news_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='latest_news.latest_news'),
        ),
    ]
