# Generated by Django 2.2.6 on 2019-11-02 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_and_actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_and_actors',
            name='news_id',
        ),
    ]
