# Generated by Django 2.2.6 on 2019-11-02 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmstars', '0001_initial'),
        ('latest_news', '0001_initial'),
        ('movie_and_actors', '0002_remove_movie_and_actors_news_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_and_actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmstars.filmstars')),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latest_news.latest_news')),
            ],
        ),
    ]
