# Generated by Django 2.2.6 on 2019-10-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_comments_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum_posts',
            name='news_dt',
        ),
    ]
