# Generated by Django 2.2.6 on 2019-10-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_auto_20191030_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Profile_Info'),
        ),
        migrations.AlterField(
            model_name='forum_posts',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Profile_Info'),
        ),
        migrations.AlterField(
            model_name='replies',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_details.User_Profile_Info'),
        ),
    ]
