# Generated by Django 2.2.6 on 2019-10-19 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_details',
            name='image',
        ),
    ]
