# Generated by Django 2.2.6 on 2019-10-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_details', '0002_remove_movie_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='movie_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
