# Generated by Django 2.2.6 on 2019-11-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmstars', '0003_auto_20191103_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmstars',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
