# Generated by Django 2.2.6 on 2019-11-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmstars', '0004_auto_20191103_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmstars',
            old_name='name',
            new_name='actor_name',
        ),
    ]
